app/myapp/urls.py
from django.urls import path
from .views import edges
from .views import points
from .views import tourists
from .views import llm
from .views import landing
from .views import simulation
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', landing.pagina_inicio, name='pagina_inicio'),
    
    # Point urls
    path('create_point/', points.create_point, name='create_point'),
    path('create_point/<int:point_id>/', points.create_point, name='edit_point'),
    path('delete_point/<int:point_id>/', points.delete_point, name='delete_point'),
    path('points/', points.get_points, name='obtener_puntos'),
    path('save_points/', points.save_points, name='save_points'),
    
    # Edge urls
    path('create_edge/', edges.create_edge, name='create_edge'),
    path('create_edge/<int:edgeId>/', edges.create_edge, name='edit_edge'),
    path('delete_edge/<int:edgeId>/', edges.delete_edge, name='delete_edge'),
    path('edges/', edges.get_edges, name='get_edges'),
    path('save_edges/', edges.save_edges, name='save_edges'),
    
    # Tourist urls
    path('create_tourist/', tourists.create_tourist, name='create_tourist'),
    path('create_tourist/<int:tourist_id>/', tourists.create_tourist, name='edit_tourist'),
    path('delete_tourist/<int:tourist_id>/', tourists.delete_tourist, name='delete_tourist'),
    path('tourists/', tourists.get_tourists, name='get_tourists'),
    path('save_tourists/', tourists.save_tourists, name='save_tourists'),
    
    # path('plan_route/', simulation.plan_route_info, name='plan_route'),
    path('view_route_description/', llm.view_route_description, name='view_route_description'),
    path('mostrar_markdown/', llm.ver_encuesta, name='mostrar_markdown'),
    path('run_simulate/', simulation.run_simulate, name='run_simulate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/planner-app/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

app/myapp/models.py
from django.db import models
from django.forms import ValidationError

class Point(models.Model):
    x = models.FloatField()
    y = models.FloatField()
    height = models.FloatField()
    point_id = models.IntegerField(unique=True)
    characteristics = models.JSONField(default=list)
    begin = models.BooleanField()
    finish = models.BooleanField()
    interesting = models.BooleanField()

    def __str__(self):
        return f"Point: {self.point_id}, location: ({self.x} ; {self.y})"
    
    def clean(self):
        if self.begin:
            if Point.objects.filter(begin=True).exclude(id=self.id).exists():
                raise ValidationError('Solo puede haber una entidad de Punto con begin en True.')
        if self.finish:
            if Point.objects.filter(finish=True).exclude(id=self.id).exists():
                raise ValidationError('Solo puede haber una entidad de Punto con finish en True.')

    def save(self, *args, **kwargs):
        self.clean()
        super(Point, self).save(*args, **kwargs)
    
class Edge(models.Model):
    point1 = models.ForeignKey(Point, related_name='edges_from', on_delete=models.CASCADE)
    point2 = models.ForeignKey(Point, related_name='edges_to', on_delete=models.CASCADE)
    distance = models.FloatField()
    characteristics = models.JSONField(default=list)

    class Meta:
        unique_together = ('point1', 'point2')

    def __str__(self):
        return f"Arista({self.point1.point_id} -> {self.point2.point_id})"
    
class Tourist(models.Model):
    name = models.CharField(unique=True, max_length=50)
    characteristics = models.JSONField(default=list)
    
    def __str__(self):
        return f"Nombre: {self.name}, Gustos: {self.characteristics})"
    

app/myapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Point, Edge, Tourist

def validate_decimal_range(value):
    if not (0 <= value <= 1):
        raise ValidationError('El valor debe estar entre 0 y 1.')

class PointForm(forms.ModelForm):
    characteristic_1 = forms.FloatField(label='Characteristic 1', validators=[validate_decimal_range])
    characteristic_2 = forms.FloatField(label='Characteristic 2', validators=[validate_decimal_range])
    characteristic_3 = forms.FloatField(label='Characteristic 3', validators=[validate_decimal_range])
    characteristic_4 = forms.FloatField(label='Characteristic 4', validators=[validate_decimal_range])

    class Meta:
        model = Point
        fields = ['x', 'y', 'height', 'point_id', 'begin', 'finish', 'interesting']

    def __init__(self, *args, **kwargs):
        super(PointForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.characteristics:
            characteristics = self.instance.characteristics
            self.fields['characteristic_1'].initial = characteristics[0] if len(characteristics) > 0 else None
            self.fields['characteristic_2'].initial = characteristics[1] if len(characteristics) > 1 else None
            self.fields['characteristic_3'].initial = characteristics[2] if len(characteristics) > 2 else None
            self.fields['characteristic_4'].initial = characteristics[3] if len(characteristics) > 3 else None
    
    def clean(self):
        cleaned_data = super().clean()
        begin = cleaned_data.get('begin')
        finish = cleaned_data.get('finish')
        interesting = cleaned_data.get('interesting')

        if sum([bool(begin), bool(finish), bool(interesting)]) > 1:
            raise ValidationError('Solo se puede marcar uno de los campos: begin, finish, interesting.')

        return cleaned_data
    
    def save(self, commit=True):
        instance = super(PointForm, self).save(commit=False)
        instance.characteristics = [
            self.cleaned_data['characteristic_1'],
            self.cleaned_data['characteristic_2'],
            self.cleaned_data['characteristic_3'],
            self.cleaned_data['characteristic_4'],
        ]
        if commit:
            instance.save()
        return instance

class EdgeForm(forms.ModelForm):
    characteristic_1 = forms.FloatField(label='Characteristic 1', validators=[validate_decimal_range])
    characteristic_2 = forms.FloatField(label='Characteristic 2', validators=[validate_decimal_range])
    characteristic_3 = forms.FloatField(label='Characteristic 3', validators=[validate_decimal_range])
    characteristic_4 = forms.FloatField(label='Characteristic 4', validators=[validate_decimal_range])

    class Meta:
        model = Edge
        fields = ['point1', 'point2', 'distance']

    def __init__(self, *args, **kwargs):
        super(EdgeForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.characteristics:
            characteristics = self.instance.characteristics
            self.fields['characteristic_1'].initial = characteristics[0] if len(characteristics) > 0 else None
            self.fields['characteristic_2'].initial = characteristics[1] if len(characteristics) > 1 else None
            self.fields['characteristic_3'].initial = characteristics[2] if len(characteristics) > 2 else None
            self.fields['characteristic_4'].initial = characteristics[3] if len(characteristics) > 3 else None

    def save(self, commit=True):
        instance = super(EdgeForm, self).save(commit=False)
        instance.characteristics = [
            self.cleaned_data['characteristic_1'],
            self.cleaned_data['characteristic_2'],
            self.cleaned_data['characteristic_3'],
            self.cleaned_data['characteristic_4'],
        ]
        if commit:
            instance.save()
        return instance
    
    def clean(self):
        cleaned_data = super().clean()
        point1 = cleaned_data.get('point1')
        point2 = cleaned_data.get('point2')      
        
        if point1 and point2 and point1.point_id >= point2.point_id:
            raise forms.ValidationError('El ID del punto 1 debe ser menor que el ID del punto 2.')

        return cleaned_data


class TouristForm(forms.ModelForm):
    characteristic_1 = forms.FloatField(label='Characteristic 1', validators=[validate_decimal_range])
    characteristic_2 = forms.FloatField(label='Characteristic 2', validators=[validate_decimal_range])
    characteristic_3 = forms.FloatField(label='Characteristic 3', validators=[validate_decimal_range])
    characteristic_4 = forms.FloatField(label='Characteristic 4', validators=[validate_decimal_range])
    characteristic_5 = forms.FloatField(label='Characteristic 5', validators=[validate_decimal_range])
    characteristic_6 = forms.FloatField(label='Characteristic 6', validators=[validate_decimal_range])

    class Meta:
        model = Tourist
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(TouristForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.characteristics:
            characteristics = self.instance.characteristics
            self.fields['characteristic_1'].initial = characteristics[0] if len(characteristics) > 0 else None
            self.fields['characteristic_2'].initial = characteristics[1] if len(characteristics) > 1 else None
            self.fields['characteristic_3'].initial = characteristics[2] if len(characteristics) > 2 else None
            self.fields['characteristic_4'].initial = characteristics[3] if len(characteristics) > 3 else None
            self.fields['characteristic_5'].initial = characteristics[4] if len(characteristics) > 4 else None
            self.fields['characteristic_6'].initial = characteristics[5] if len(characteristics) > 5 else None

    def save(self, commit=True):
        instance = super(TouristForm, self).save(commit=False)
        instance.characteristics = [
            self.cleaned_data['characteristic_1'],
            self.cleaned_data['characteristic_2'],
            self.cleaned_data['characteristic_3'],
            self.cleaned_data['characteristic_4'],
            self.cleaned_data['characteristic_5'],
            self.cleaned_data['characteristic_6'],
        ]
        if commit:
            instance.save()
        return instance

app/myapp/views/edges.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, render

import json

from .points import save_map_img

from ..models import Edge
from ..forms import EdgeForm

def create_edge(request, edgeId=None):
    if edgeId:
        edge = get_object_or_404(Edge, id=edgeId)
    else:
        edge = None

    if request.method == 'POST':
        form = EdgeForm(request.POST, instance=edge)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = EdgeForm(instance=edge)
        
    edges = Edge.objects.all()
    return render(request, 'create_edge.html', {'form': form, 'edges':edges, 'edge':edge})

def delete_edge(request, edgeId):
    edge = get_object_or_404(Edge, id=edgeId)
    edge.delete()
    return redirect('create_edge')

def get_edges(request):
    edges = list(Edge.objects.values())
    return JsonResponse(edges, safe=False)

def save_edges(request):
    edges = list(Edge.objects.all().values())
    if len(edges) > 0:
        # Guardar los datos de los caminos
        with open('./myapp/utils/edges_data.json', 'w') as file:
            json.dump(edges, file, indent=4)
        save_map_img()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': 'No hay caminos guardados'})
   

app/myapp/views/landing.py
from django.shortcuts import render

def pagina_inicio(request):
    return render(request, 'index.html')

app/myapp/views/llm.py
from django.shortcuts import render
from django.http import JsonResponse

import json
import markdown

from ..llm import show_info_route
from ..utils.map_utils import Map
from ..modules.module_1.module_1 import plan_route


def view_route_description(request):
    # Cargamos los datos del mapa
    map_data = Map()
    
    # Cargamos los datos de los turistas
    with open('./myapp/utils/route_data.json', 'r') as file:
        route = json.load(file)
    
    interesting_points = []
    for goal in route:
        interesting_points.append({
            'id': goal,
            'location': map_data.points[goal].location,
            'height': map_data.points[goal].height,
            'characteristics':map_data.points[goal].characteristics
        }) 

    info = show_info_route(interesting_points)

    return render(request, 'route_info.html', {'info': info})

    
def ver_encuesta(request):
    # Leer el contenido del archivo Markdown
    with open('./myapp/modules/module_0/info.md', 'r', encoding='utf-8') as file:
        contenido_markdown = file.read()

    # Convertir el contenido Markdown a HTML
    contenido_html = markdown.markdown(contenido_markdown)

    # Pasar el contenido HTML al template
    return render(request, 'survey.html', {'contenido_html': contenido_html})

app/myapp/views/points.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render, redirect

import json
import networkx as nx
import matplotlib.pyplot as plt

from ..models import Point
from ..forms import PointForm


def create_point(request, point_id=None):
    if point_id:
        point = get_object_or_404(Point, id=point_id)
    else:
        point = None

    if request.method == 'POST':
        form = PointForm(request.POST, instance=point)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = PointForm(instance=point)
    
    points = Point.objects.all()
    return render(request, 'create_point.html', {'form': form, 'points': points, 'point': point})

def delete_point(request, point_id):
    point = get_object_or_404(Point, id=point_id)
    point.delete()
    return redirect('create_point')

def get_points(request):
    puntos = list(Point.objects.all().values())
    return JsonResponse(puntos, safe=False)

def save_points(request):
    points = list(Point.objects.all().values())
    if len(points) > 0:
        # Guardar los datos de los puntos
        with open('./myapp/utils/points_data.json', 'w') as file:
            json.dump(points, file, indent=4)
        save_map_img()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': 'No hay turistas guardados'})
 

def save_map_img():
    # Cargamos los datos
    with open('./myapp/utils/points_data.json', 'r') as file1:
        points = json.load(file1)
        
    # Cargamos los datos
    with open('./myapp/utils/edges_data.json', 'r') as file2:
        edges = json.load(file2)
    
    # Crear el grafo
    G = nx.Graph()

    # Estira la imagen
    factor_x = 2  # Factor de estiración en el eje X
    factor_y = 1    # Factor de estiración en el eje Y

    stretched_points = []
    for point in points:
        stretched_x = point['x'] * factor_x
        stretched_y = point['y'] * factor_y
        stretched_points.append({
            'point_id': point['point_id'],
            'x': stretched_x,
            'y': stretched_y,
            'height': point['height'],
            'characteristics': point['characteristics']
        })

    # Añadir nodos estirados
    for stretched_point in stretched_points:
        G.add_node(stretched_point['point_id'], pos=(stretched_point['x'], stretched_point['y']), height=stretched_point['height'], characteristics=stretched_point['characteristics'])

    # Añadir aristas
    for edge in edges:
        G.add_edge(edge['point1_id'], edge['point2_id'], distance=edge['distance'], characteristics=edge['characteristics'])

    # Dibujar el grafo
    pos = nx.get_node_attributes(G, 'pos')
    nx.draw_networkx(G, pos, with_labels=True, node_size=500, node_color='skyblue', font_size=10, font_color='black')

    # Añadir gráficos de barras cerca de cada nodo
    for stretched_point in stretched_points:
        x, y = stretched_point['x'], stretched_point['y']
        characteristics = stretched_point['characteristics']

    # Guardar la imagen en formato SVG
    plt.savefig('./static/images/map.svg', format='svg', dpi=300, bbox_inches='tight')

app/myapp/templates/create_point.html
<!DOCTYPE html>
<html>
<head>
    <title>Crear mapa</title>
    <script>

        function handleFormSubmit(event) {
            event.preventDefault();
            const form = event.target;
            const formData = new FormData(form);

            fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': form.querySelector('[name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Punto guardado satisfactoriamente!');
                    window.location.href = 'http://127.0.0.1:8000/create_point';  // Redirigir a la página de creación de puntos
                } else {
                    alert('Fallo en guardar el punto: ' + JSON.stringify(data.errors));
                }
            })
            .catch(error => {
                alert('Ocurrió un error: ' + error);
            });
        }

        function handleDelete(event, pointId) {
            event.preventDefault();
            if (confirm('Estás seguro de querer eliminar este punto?')) {
                fetch(`/delete_point/${pointId}/`, {
                    method: 'GET',
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                    }
                })
                .then(response => {
                    if (response.ok) {
                        alert('Punto eliminado satisfactoriamente!');
                        location.reload();  // Recargar la página para actualizar la lista de puntos
                    } else {
                        alert('Fallo al eliminar el punto.');
                    }
                })
                .catch(error => {
                    alert('Ocurrió un error: ' + error);
                });
            }
        }

        async function getPoints() {
            const response = await fetch('/points');
            const points = await response.json();
            return points;
        }
        
        async function savePoints() {
            const points = await getPoints();
            const blob = new Blob([JSON.stringify(points)], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'points.json';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            
            fetch(`/save_points/`, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => {
                if (!response.ok) {
                    alert('Puntos guardados.');
                }
            })
            .catch(error => {
                alert('Ocurrió un error: ' + error);
            });
        }
        
    </script>
    <!-- Incluir Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    {% load widget_tweaks %}
</head>
<body class="m-5">
    <div class="row">
        <div class="col-md-4 mr-5">
            <h1>Guardar un punto</h1>
            <p class="mb-4">Los valores de las características deben estar entre 0 y 1</p>
            <form method="post" action="{% if point %}{% url 'edit_point' point.id %}{% else %}{% url 'create_point' %}{% endif %}" onsubmit="handleFormSubmit(event)" class="mb-4 text-right">
                {% csrf_token %}
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_point_id">ID Punto</label>
                    {{ form.point_id|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_x">Coordenada X</label>
                    {{ form.x|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_y">Coordenada Y</label>
                    {{ form.y|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_height">Altura</label>
                    {{ form.height|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_1">Variedad de flora</label>
                    {{ form.characteristic_1|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_2">Variedad de fauna</label>
                    {{ form.characteristic_2|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_3">Sitios históricos</label>
                    {{ form.characteristic_3|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_4">Sitios con ríos</label>
                    {{ form.characteristic_4|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_begin">Entrada</label>
                    {{ form.begin|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_finish">Salida</label>
                    {{ form.finish|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_interesting">Interesante</label>
                    {{ form.interesting|add_class:"form-control w-50" }}
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
        <div class="col-md-7 ml-5">
            <h2>Lista de puntos</h2>
            <ul class="list-group">
                {% for point in points %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Punto {{ point.point_id }}, ({{ point.x }} ; {{ point.y }}), altura: {{ point.height }}, características: {{ point.characteristics }}
                    {% if point.begin %}
                        <span class="badge bg-success text-light">Entrada</span>
                    {% elif point.finish %}
                        <span class="badge bg-danger text-light">Salida</span>
                    {% elif point.interesting %}
                        <span class="badge bg-primary text-light">Interesante</span>
                    {% endif %}
                    <span>
                        <a href="{% url 'edit_point' point.id %}" class="btn btn-secondary btn-sm">Edit</a>
                        <a href="#" onclick="handleDelete(event, {{ point.id }})" class="btn btn-danger btn-sm">Delete</a>
                    </span>
                </li>
                
                {% endfor %}
            </ul>
        </div>
        <div class="d-flex justify-content-between w-100">
            <button class="btn btn-danger" onclick="window.location.href='http://127.0.0.1:8000/'">Inicio</button>
            <button class="btn btn-success" onclick="savePoints()">Descargar puntos</button>
        </div> 
    </div>
</body>
</html>

app/myapp/templates/create_tourist.html
<!DOCTYPE html>
<html>
<head>
    <title>Crear Turistas</title>
    <script>

        function handleFormSubmit(event) {
            event.preventDefault();
            const form = event.target;
            const formData = new FormData(form);

            fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': form.querySelector('[name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Turista guardado satisfactoriamente!');
                    window.location.href = 'http://127.0.0.1:8000/create_tourist';
                } else {
                    alert('Fallo en guardar el turista: ' + JSON.stringify(data.errors));
                }
            })
            .catch(error => {
                alert('Ocurrió un error: ' + error);
            });
        }

        function handleDelete(event, touristId) {
            event.preventDefault();
            if (confirm('Estás seguro que deseas eliminar este turista?')) {
                fetch(`/delete_tourist/${touristId}/`, {
                    method: 'GET',
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                    }
                })
                .then(response => {
                    if (response.ok) {
                        alert('Turista eliminado satisfactoriamente!');
                        location.reload();
                    } else {
                        alert('Fallo en eliminar al turista.');
                    }
                })
                .catch(error => {
                    alert('Ocurrió un error: ' + error);
                });
            }
        }

        async function getTourists() {
            const response = await fetch('/tourists');
            const tourists = await response.json();
            console.log(tourists)
            return tourists;
        }
        
        async function saveTourists() {
            const tourists = await getTourists();
            const blob = new Blob([JSON.stringify(tourists)], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'tourists.json';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);

            
            fetch(`/save_tourists/`, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => {
                if (!response.ok) {
                    alert('Turistas guardados.');
                }
            })
            .catch(error => {
                alert('Ocurrió un error: ' + error);
            });
        }
        
    </script>
    <!-- Incluir Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    {% load widget_tweaks %}
</head>
<body class="m-5">
    <div class="row">
        <div class="col-md-4 mr-5">
            <h1>Guardar un Turista</h1>
            <p class="mb-4">Los valores de las características deben estar entre 0 y 1</p>
            <form method="post" action="{% if tourist %}{% url 'edit_tourist' tourist.id %}{% else %}{% url 'create_tourist' %}{% endif %}" onsubmit="handleFormSubmit(event)" class="mb-4 text-right">
                {% csrf_token %}
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_name">Nombre</label>
                    {{ form.name|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_1">Caminos poco transitados</label>
                    {{ form.characteristic_1|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_2">Superación física</label>
                    {{ form.characteristic_2|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_3">Variedad de flora</label>
                    {{ form.characteristic_3|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_4">Variedad de fauna</label>
                    {{ form.characteristic_4|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_5">Sitios históricos</label>
                    {{ form.characteristic_5|add_class:"form-control w-50" }}
                </div>
                <div class="form-group d-flex justify-content-end">
                    <label class="mr-3" for="id_characteristic_6">Sitios con ríos</label>
                    {{ form.characteristic_6|add_class:"form-control w-50" }}
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
        <div class="col-md-7 ml-5">
            <h2>Lista de turistas</h2>
            <ul class="list-group">
                {% for tourist in tourists %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Nombre: "{{ tourist.name }}", características: {{ tourist.characteristics }}
                        <span>
                            <a href="{% url 'edit_tourist' tourist.id %}" class="btn btn-secondary btn-sm">Edit</a>
                            <a href="#" onclick="handleDelete(event, {{ tourist.id }})" class="btn btn-danger btn-sm">Delete</a>
                        </span>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="d-flex justify-content-between w-100">
            <button class="btn btn-danger" onclick="window.location.href='http://127.0.0.1:8000/'">Inicio</button>
            <button class="btn btn-success" onclick="saveTourists()">Descargar turistas</button>
        </div> 
    </div>
</body>
</html>